/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorObj
 */
export interface ErrorObj {
    /**
     * 
     * @type {string}
     * @memberof ErrorObj
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof ErrorObj
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ErrorObj
     */
    'title'?: string | null;
    /**
     * 
     * @type {object}
     * @memberof ErrorObj
     */
    'data'?: object | null;
}

