/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LztRate } from './lzt-rate';
// May contain unused imports in some cases
// @ts-ignore
import type { Max } from './max';
// May contain unused imports in some cases
// @ts-ignore
import type { Min } from './min';

/**
 * 
 * @export
 * @interface OrderDataOut
 */
export interface OrderDataOut {
    /**
     * 
     * @type {number}
     * @memberof OrderDataOut
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof OrderDataOut
     */
    'nickname': string;
    /**
     * 
     * @type {number}
     * @memberof OrderDataOut
     */
    'rating': number;
    /**
     * 
     * @type {string}
     * @memberof OrderDataOut
     */
    'pm_name': string;
    /**
     * 
     * @type {Min}
     * @memberof OrderDataOut
     */
    'min': Min;
    /**
     * 
     * @type {Max}
     * @memberof OrderDataOut
     */
    'max': Max;
    /**
     * 
     * @type {boolean}
     * @memberof OrderDataOut
     */
    'round_up': boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderDataOut
     */
    'comment': string;
    /**
     * 
     * @type {LztRate}
     * @memberof OrderDataOut
     */
    'lzt_rate': LztRate;
    /**
     * 
     * @type {string}
     * @memberof OrderDataOut
     */
    'bot_username': string;
}

