/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AmountOnCurrency } from './amount-on-currency';
// May contain unused imports in some cases
// @ts-ignore
import type { BotPaymentDTO } from './bot-payment-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { OwnerSecurityDeposit } from './owner-security-deposit';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentOutDTO } from './payment-out-dto';

/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof Payment
     */
    'cancellable': boolean;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    'bot': string;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    'order_id': number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    'payment_id': number;
    /**
     * 
     * @type {number}
     * @memberof Payment
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    'payment_method_type': string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    'requisites': string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    'currency': string;
    /**
     * 
     * @type {AmountOnCurrency}
     * @memberof Payment
     */
    'amount_on_currency': AmountOnCurrency;
    /**
     * 
     * @type {OwnerSecurityDeposit}
     * @memberof Payment
     */
    'owner_security_deposit': OwnerSecurityDeposit;
}

