/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SetStatusOutDTO } from './set-status-out-dto';

/**
 * 
 * @export
 * @interface StatusErrorObj
 */
export interface StatusErrorObj {
    /**
     * 
     * @type {string}
     * @memberof StatusErrorObj
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof StatusErrorObj
     */
    'message': string;
    /**
     * 
     * @type {SetStatusOutDTO}
     * @memberof StatusErrorObj
     */
    'payment': SetStatusOutDTO;
}

