/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CancelActivePaymentRequest } from '../models';
// @ts-ignore
import type { CloseActivePaymentOut } from '../models';
// @ts-ignore
import type { ErrorObj } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * APIApi - axios parameter creator
 * @export
 */
export const APIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * :param request: :param body: :return:  Ищет активные платежи пользователя. is_cancel - просто отменит платеж.  В противном случае отправит сообщение с платежом в бота. При вызове без флага is_cancel,   стоит отправить пользователя в бота и закрыть приложение
         * @summary Miniapp Active Payment
         * @param {CancelActivePaymentRequest} cancelActivePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost: async (cancelActivePaymentRequest: CancelActivePaymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cancelActivePaymentRequest' is not null or undefined
            assertParamExists('miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost', 'cancelActivePaymentRequest', cancelActivePaymentRequest)
            const localVarPath = `/market/mini_app/calc_order/active_payment`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cancelActivePaymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * APIApi - functional programming interface
 * @export
 */
export const APIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = APIApiAxiosParamCreator(configuration)
    return {
        /**
         * :param request: :param body: :return:  Ищет активные платежи пользователя. is_cancel - просто отменит платеж.  В противном случае отправит сообщение с платежом в бота. При вызове без флага is_cancel,   стоит отправить пользователя в бота и закрыть приложение
         * @summary Miniapp Active Payment
         * @param {CancelActivePaymentRequest} cancelActivePaymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(cancelActivePaymentRequest: CancelActivePaymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CloseActivePaymentOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(cancelActivePaymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIApi.miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * APIApi - factory interface
 * @export
 */
export const APIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = APIApiFp(configuration)
    return {
        /**
         * :param request: :param body: :return:  Ищет активные платежи пользователя. is_cancel - просто отменит платеж.  В противном случае отправит сообщение с платежом в бота. При вызове без флага is_cancel,   стоит отправить пользователя в бота и закрыть приложение
         * @summary Miniapp Active Payment
         * @param {APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(requestParameters: APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CloseActivePaymentOut> {
            return localVarFp.miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(requestParameters.cancelActivePaymentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost operation in APIApi.
 * @export
 * @interface APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest
 */
export interface APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest {
    /**
     * 
     * @type {CancelActivePaymentRequest}
     * @memberof APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost
     */
    readonly cancelActivePaymentRequest: CancelActivePaymentRequest
}

/**
 * APIApi - object-oriented interface
 * @export
 * @class APIApi
 * @extends {BaseAPI}
 */
export class APIApi extends BaseAPI {
    /**
     * :param request: :param body: :return:  Ищет активные платежи пользователя. is_cancel - просто отменит платеж.  В противном случае отправит сообщение с платежом в бота. При вызове без флага is_cancel,   стоит отправить пользователя в бота и закрыть приложение
     * @summary Miniapp Active Payment
     * @param {APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIApi
     */
    public miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(requestParameters: APIApiMiniappActivePaymentMarketMiniAppCalcOrderActivePaymentPostRequest, options?: RawAxiosRequestConfig) {
        return APIApiFp(this.configuration).miniappActivePaymentMarketMiniAppCalcOrderActivePaymentPost(requestParameters.cancelActivePaymentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

